site_name: OpenTriviaDB

plugins:
  - search
  - autorefs
  - mkdocstrings:
      custom_templates: docs/templates
      handlers:
        python:
          options:
            # members_order: source
            # heading_level: 3
            docstring_style: numpy
            # docstring_section_style: list
            show_signature_annotations: true
            separate_signature: true
  - include-markdown

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true

theme:
  name: material
  # custom_dir: docs/overrides

  palette:
    scheme: slate
    accent: orange

  font:
    text: Roboto # Anek Devanagari
    code: Roboto Mono # Oxygen Mono

  logo: https://opentdb.com/images/logo.png

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - content.tabs.link

  icon:
    repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/opentriviadb/
      name: PyPI
    - icon: fontawesome/brands/github
      link: https://github.com/parafoxia/opentriviadb
      name: Source

copyright: Copyright &copy; 2022-present Ethan Henderson

repo_name: parafoxia/opentriviadb
repo_url: https://github.com/parafoxia/opentriviadb

nav:
  - "index.md"
  - "Reference":
    - "client.md"
    - "questions.md"
    - "errors.md"
